# Server jar name, it is used for replacing by correct version of PaperMC, when is force-map-version set to true
server-file-name: server.jar
# When is set to true, is tries to download correct Minecraft version by map version
force-map-version: false
# This is example, how can be map configured
map:
  # Map name, must be configured, you can use colors (example: &a&lOMG &c&nMaRiO &eSUPERMAP)
  name: "&b&lLast Breath"
  # Map Minecraft version, must be configured
  mc-version: 1.16.3
  # Minecraft world name, when will be map placed
  world-name: world
  # Link for download map zip
  world-url: https://upload.hicoria.com/files/qxEd13NF.zip
  # Link of zip resourcepack, when you don't want to use resourcepack set quotation marks only (Default Minecraft launcher java don't support Let's encrypt certificates)
  resource-pack-url: "https://upload.hicoria.com/files/rbAhKexY.zip"
  # SHA1 of resource pack
  resource-pack-sha1: 3980d40646934e544163a359fa0387eaa4cbe017
  # When is set to true, players what don't allow to download resource pack, will be kicked
  deny-join-without-resource-pack: true
  # Link for map website, must be configured
  website: https://bit.ly/35gWAkX
  # Map author, must be configured
  author: Command Builders
  # Player-limit of map, must be configured
  limit: 4