name: AdventureMapManager
version: ${project.version}
main: eu.thevelda.adventuremapmanager.Main
api-version: 1.16
load: STARTUP
authors: [ Velda ]
description: Plugin for manage Minecraft adventure maps on Minecraft server.
softdepend: [PlaceholderAPI]
commands:
  map:
    description: Command, that shows basic info about map, what are you playing.